namespace Language.Analysis.CodeAnalysis.Syntax;

public enum SyntaxKind
{
    // tokens
    IdentifierToken,
    NumberToken,
    StringToken,
    WhitespaceToken,
    PlusToken,
    MinusToken,
    StarToken,
    SlashToken,
    OpenParenthesisToken,
    CloseParenthesisToken,
    BadToken,
    EndOfFileToken,
    BangToken,
    AmpersandAmpersandToken,
    PipePipeToken,
    EqualsEqualsToken,
    BangEqualsToken,
    EqualsToken,
    OpenBraceToken,
    CloseBraceToken,
    SemicolonToken,
    LessOrEqualsToken,
    LessToken,
    GreaterOrEqualsToken,
    GreaterToken,
    PipeToken,
    AmpersandToken,
    HatToken,
    TildeToken,
    CommaToken,   
    DotToken,

    // keywords
    TrueKeyword,
    FalseKeyword,
    VarKeyword,
    LetKeyword,
    WhileKeyword,
    IfKeyword,
    ElseKeyword,
    ForKeyword,
    FunctionKeyword,
    BreakKeyword,
    ContinueKeyword,
    ReturnKeyword,
    ClassKeyword,
    ThisKeyword,
    NewKeyword,
    StaticKeyword,

    // nodes
    CompilationUnit,
    VariableDeclarationSyntax,
    VariableDeclarationAssignmentSyntax,
    TypeClause,
    InheritanceClause,
    ClassDeclaration,
    MethodDeclaration,
    FieldDeclaration,
    GlobalStatement,
    Parameter,
    
    // expressions
    LiteralExpression,
    BinaryOperatorExpression,
    ParenthesizedExpression,
    UnaryExpression,
    AssignmentExpression,
    NameExpression,
    MethodCallExpression,
    ObjectCreationExpression,
    MemberAccessExpression,
    MemberAssignmentExpression,
    ThisExpression,

    // statements
    BlockStatement,
    ExpressionStatement,
    WhileStatement,
    VariableDeclarationStatement,
    IfStatement,
    ElseClause,   
    ForStatement,
    ColonToken,
    ContinueStatement,
    BreakStatement,
    ReturnStatement,
    VariableDeclarationAssignmentStatement,
}