namespace Language.CodeAnalysis.Syntax;

public enum SyntaxKind
{
    // tokens
    IdentifierToken,
    NumberToken,
    StringToken,
    WhitespaceToken,
    PlusToken,
    MinusToken,
    StarToken,
    SlashToken,
    OpenParenthesisToken,
    CloseParenthesisToken,
    BadToken,
    EndOfFileToken,
    BangToken,
    AmpersandAmpersandToken,
    PipePipeToken,
    EqualsEqualsToken,
    BangEqualsToken,
    EqualsToken,
    OpenBraceToken,
    CloseBraceToken,
    SemicolonToken,
    LessOrEqualsToken,
    LessToken,
    GreaterOrEqualsToken,
    GreaterToken,
    PipeToken,
    AmpersandToken,
    HatToken,
    TildeToken,
    CommaToken,   
    DotToken,

    // keywords
    TrueKeyword,
    FalseKeyword,
    VarKeyword,
    LetKeyword,
    WhileKeyword,
    IfKeyword,
    ElseKeyword,
    ForKeyword,
    FunctionKeyword,
    BreakKeyword,
    ContinueKeyword,
    ReturnKeyword,
    ClassKeyword,
    ThisKeyword,
    NewKeyword,

    // nodes
    CompilationUnit,
    VariableDeclarationSyntax,
    VariableDeclarationAssignmentSyntax,
    TypeClause,
    ClassDeclaration,
    FunctionDeclaration,
    FieldDeclaration,
    GlobalStatement,
    Parameter,
    
    // expressions
    LiteralExpression,
    BinaryOperatorExpression,
    ParenthesizedExpression,
    UnaryExpression,
    AssignmentExpression,
    NameExpression,
    MethodCallExpression,
    ThisExpression,
    ObjectCreationExpression,
    FieldAssignmentExpression,
    
    // statements
    BlockStatement,
    ExpressionStatement,
    WhileStatement,
    VariableDeclarationStatement,
    IfStatement,
    ElseClause,   
    ForStatement,
    ColonToken,
    ContinueStatement,
    BreakStatement,
    ReturnStatement,
 
}